# Generated by Django 4.0.6 on 2022-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQ00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('inventory_doc', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('store', models.IntegerField()),
                ('supplier', models.CharField(max_length=50)),
                ('theoritical_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entred_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deviation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deviation_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dev', models.CharField(max_length=10)),
                ('division', models.IntegerField()),
                ('delete', models.CharField(max_length=10)),
                ('date_catchment', models.DateField()),
                ('corrected_by', models.CharField(max_length=50)),
                ('catchment', models.CharField(max_length=50)),
                ('refecrence_inventory', models.CharField(max_length=50)),
                ('inventory_number', models.IntegerField()),
                ('Tys', models.IntegerField()),
            ],
        ),
    ]
