# Generated by Django 4.0.6 on 2022-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_accuracy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq00',
            name='Tys',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='catchment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='corrected_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='date_catchment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='delete',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='dev',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='inventory_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='refecrence_inventory',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='supplier',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
