# Generated by Django 4.0.6 on 2022-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_accuracy', '0004_alter_sq00_inventory_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq00',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='material',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='store',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
