# Generated by Django 4.0.6 on 2022-07-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_accuracy', '0005_alter_sq00_designation_alter_sq00_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sq00',
            name='deviation',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='deviation_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='entred_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sq00',
            name='theoritical_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
